### ISSUE TITLE
Each subscribe new redis connection

### ISSUE THREAD

**Issue by manish-tech-expert** [abhinavsingh/async_pubsub#3]
Hello Abhinav 

i really like your script but in each subscribe new redis connection.so it's not scale in case of maximum connection like 100k

**Comment by abhinavsingh** [comment]
@manish03121991 Thank you :)  I am glad you like it.

You are probably referring to this particular line of invocation https://github.com/abhinavsingh/async_pubsub/blob/master/async_pubsub/redis_pubsub.py#L47

where `r = RedisPubSub.get_redis()` is returning a new connection every time.

You are correct!!!  We should be establishing a single client connection within [constructor](https://github.com/abhinavsingh/async_pubsub/blob/master/async_pubsub/redis_pubsub.py#L11) and re-use the same Redis connection.

Do you want to send out a PR?

**Comment by manish-tech-expert** [comment]
Assume if each channel are unique for each user .....
then we subscribe each channel and it connect each time...

```
self.r = RedisPubSub(host='127.0.0.1', port=6379, callback=self.callback)
self.r.connect() 
```

and it will create new connection

**Comment by abhinavsingh** [comment]
Frankly, I think you don't need `RedisPubSub` class for publish part.  `publish` method is just a convenience, it's equivalent to calling

```
r = redis.StrictRedis(
            host = '127.0.0.1',
            port = 6379,
            db   = 0
        )
r.publish(channel_id, message)
```

^^^ This forces a new connection every time you call `RedisPubSub.publish`, example here https://github.com/abhinavsingh/async_pubsub/blob/master/examples/redis_publish.py

If you don't want above behavior and want to achieve 100k publish event concurrency better just publish the message yourself:

```
r = redis.StrictRedis(
            host = '127.0.0.1',
            port = 6379,
            db   = 0
        )
for i in range(100000):
    r.publish(channel_id, message)
```
